// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::models::enums::*;
use chrono::NaiveDateTime;
use bigdecimal::BigDecimal;
use diesel::Queryable;

#[derive(Queryable, Debug)]
pub struct Booking {
    pub id: i32,
    pub user_id: Option<i32>,
    pub trip_id: Option<i32>,
    pub seat_id: Option<i32>,
    pub booking_time: NaiveDateTime,
    pub status: BookingStatusEnum,
}

#[derive(Queryable, Debug)]
pub struct Bus {
    pub id: i32,
    pub bus_number: String,
    pub bus_type: BusTypeEnum,
    pub capacity: i32,
    pub org_name: Option<String>,
    pub created_at: Option<NaiveDateTime>,
    pub organization_id: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Busroute {
    pub id: i32,
    pub route_number: String,
    pub start_location: String,
    pub end_location: String,
    pub distance: i32,
    pub travel_time: i32,
}

#[derive(Queryable, Debug)]
pub struct Cancellation {
    pub id: i32,
    pub booking_id: Option<i32>,
    pub user_id: Option<i32>,
    pub reason: Option<String>,
    pub refund_amount: Option<BigDecimal>,
    pub refund_status: Option<RefundStatusEnum>,
    pub created_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Driver {
    pub id: i32,
    pub driver_name: String,
    pub driver_age: i32,
    pub driver_phone: String,
    pub driver_license_number: String,
    pub license_type: LicenseEnum,
}

#[derive(Queryable, Debug)]
pub struct OrganizationRating {
    pub id: i32,
    pub organization_id: Option<i32>,
    pub user_id: Option<i32>,
    pub rating: Option<i32>,
    pub review: Option<String>,
    pub created_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Organization {
    pub id: i32,
    pub name: String,
    pub contact_email: Option<String>,
    pub contact_phone: Option<String>,
    pub address: Option<String>,
    pub gst_number: Option<String>,
    pub created_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Payment {
    pub id: i32,
    pub booking_id: i32,
    pub amount: BigDecimal,
    pub payment_method: PaymentTypeEnum,
    pub status: Option<PaymentStatusEnum>,
    pub transaction_id: Option<String>,
    pub created_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Rating {
    pub id: i32,
    pub booking_id: i32,
    pub user_id: i32,
    pub bus_id: i32,
    pub driver_id: Option<i32>,
    pub operator_id: Option<i32>,
    pub rating: i32,
    pub review: Option<String>,
    pub created_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Seat {
    pub id: i32,
    pub trip_id: Option<i32>,
    pub bus_id: Option<i32>,
    pub seat_number: i32,
    pub is_booked: bool,
}

#[derive(Queryable, Debug)]
pub struct Trip {
    pub id: i32,
    pub bus_id: Option<i32>,
    pub route_id: Option<i32>,
    pub arrival_time: NaiveDateTime,
    pub departure_time: NaiveDateTime,
    pub starting_location: String,
    pub price: BigDecimal,
    pub status: TripStatusEnum,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub email: String,
    pub phone: String,
    pub password: String,
}

